In [43]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [44]:
df = pd.read_csv("Truck_data_Labeled_random_leaders.csv")
df.head()

   years_of_experience  aerodynamics_score  technological_score  Leader
0                    4                  45                   10       1
1                    6                  29                    7       0
2                    8                  34                    9       0
3                    5                  50                    9       1
4                    4                  19                    8       0

In [45]:
leader = df[df.Leader==1]
leader.shape

(1579, 4)

In [46]:
NOT_Leader = df[df.Leader==0]
NOT_Leader.shape

(3421, 4)

In [47]:
X = df[['years_of_experience','aerodynamics_score','technological_score']]
X.head()

   years_of_experience  aerodynamics_score  technological_score
0                    4                  45                   10
1                    6                  29                    7
2                    8                  34                    9
3                    5                  50                    9
4                    4                  19                    8

In [48]:
Y = df.Leader
Y.head()

0    1
1    0
2    0
3    1
4    0
Name: Leader, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=0.8)

In [50]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
model = RandomForestClassifier()

In [52]:
model.fit(X_train, Y_train)

RandomForestClassifier()

In [53]:
x_pred=model.predict(X_test)

In [54]:
model.predict_proba(X_test)
X_test

      years_of_experience  aerodynamics_score  technological_score
2976                   10                  25                    3
1960                   12                  43                    4
1140                    7                  25                    3
522                    14                  30                    1
3561                   13                  29                    9
...                   ...                 ...                  ...
2571                   11                  48                    2
3403                   19                  31                   10
4056                   11                  10                    9
3306                   13                  19                    3
385                    18                  31                    7

[1000 rows x 3 columns]

In [55]:
model.score(X_test,Y_test)

0.902

In [56]:
test = pd.read_csv("test.csv")
test.head()

   years_of_experience  aerodynamics_score  technological_score
0                    4                   5                   10
1                    2                  19                    5
2                    5                  20                    7

In [57]:

model.predict(test)

array([0, 0, 0], dtype=int64)

In [58]:
import numpy as np
probs=model.predict_proba(test)
probs

array([[0.97, 0.03],
       [1.  , 0.  ],
       [0.88, 0.12]])

In [59]:
arr = []
probs_percent = probs * 100
leading_probability = float('-inf')
Truck_num = 0
index = 0
for row in probs_percent:
    print(row[1])
    arr.append(row[1])

sorted(arr, reverse=True)

3.0
0.0
11.999999999999998

[11.999999999999998, 3.0, 0.0]

In [60]:
for row in probs_percent:
    #index += 1
    if row[1] > leading_probability:
        leading_probability = row[1]
        Truck_num = index+1
    index += 1

In [61]:
Truck_num

3

In [62]:
leading_probability

11.999999999999998

In [63]:
import random

follower_num = random.choice([1, 2, 3])
while follower_num == Truck_num:  # Ensure follower number is different from the predicted number
    follower_num = random.choice([1, 2, 3])
follower_num

1